### PR TITLE
Cursor

### PR DESCRIPTION
**Pull request by hepfnepf**
Added in the cursors of the original game and a management script. The script gets loaded in autoload so the cursor will always be set and can be changed in every scene. It provides the ability to set the cursor to one of the new cursors and to get the currently used cursor. This means tough, that the cursor shuld always be changed from within the cursor script. Else the value of the current_cursor will not be right since godot does not seem to have any Input.get_cursor() method.

### CODE REVIEW

**Comment by hepfnepf** [comment]
I dont quite get what the output of the check is trying to tell me. Can someone pls explain it to me?

**Comment by LinuxDonald** [comment]
It runs this script: https://github.com/unknown-horizons/godot-port/blob/develop/file_format.sh

And check if the code is formated correctly. As i see we don't have written that down in our wiki...

**Comment by LinuxDonald** [comment]
@artism90 please review it.

**Comment by LinuxDonald** [comment]
I will look this week whats up with formatting and merge it than.

**Comment by LinuxDonald** [comment]
@Burkhard1979 @hisoka999 maybe one of you both can help here with the formating error please?

**Comment by Burkhard1979** [comment]
@LinuxDonald I cannot update this pull request (If I can, please tell me how, otherwise the fix is in pull request #84 )

**Pull request merged**
