### PR TITLE
Update Unknown Horizons to Godot 3.2.3

### PR DESCRIPTION
**Pull request by pingwindev**
- Went through all scenes and opened/saved them.
- Increased Godot's message queue memory limit to 2048, as 1024 turns out to be too low.
- Updated `WorldThing`'s `texture` setter to additionally set `albedo_texture`. As of 3.2.3, this is now primarily rendered when a material is in use. The same for the `Huker`'s `FactionColor` material.
- Edited scripts accessing a singleton enum slightly to fix errors caused by https://github.com/godotengine/godot/issues/14681.
- Some refactoring and minor fixes.

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
Since Godot 3.2.3 automatically removed some lines in `project.godot`, I added one commit with those changes. This PR looks good and works fine in Godot 3.2.3.

**Comment by pingwindev** [comment]
@aaronfranke Is it a new flag in the user settings or something I'm not aware of? On my end, it keeps readding the removed lines on each project opening (using 3.2.3 stable non-Mono). Also, it's strange that some of those removed classes are in fact not empty at all and contain some actual logic (take the first two for instance, **Alvearies.gd** and **Bakery.gd**). So I'm a bit baffled why they got removed in the first place.

**Comment by aaronfranke** [comment]
Hm, that's weird. Maybe try deleting `.import/` and see if the same thing happens. If those lines regenerate for you then I guess you can commit them, though I'm confused as to why we're getting different results, might be a Godot bug.

**Comment by pingwindev** [comment]
Wiped my `.import/`, it was a burning dumpster by now anyway (before 9378 files / 823 MiB, now 2662 files / 486 MiB). Lines are still being regenerated though. Guess, I'll just commit them then.

**Pull request merged**
