### PR TITLE
Building Base Type

### PR DESCRIPTION
**Pull request by yigitozdemir**
Added base scene for building. Building scenes like stone_house may be created via extending base Building scene. 

We can develop common method and attributes in Building.tscn and Building.gd.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
This is not right, `WorldThing` is supposed to be a low level class to anything that visually appears in the world, and not a `Building` class of its own. A new `Building` class should be made inheriting `WorldThing`'s script and scene.

**Comment by yigitozdemir** [comment]
I'll update source according to your comment tomorrow. It's seems like you are rights. That might be better for for this case.

**Comment by yigitozdemir** [comment]
WorldThing came back. Now, Building scene extends WorldThing also Stone_house scene extends building.

**Comment by YeldhamDev** [comment]
I jumped in and did a basic layout of how this should go (ac1a15f0c0b0b2fc5e5b4385e87aa0aa414ef079). Created two classes: `Building`, which inherents `WorldThing`, and `Residence`, which inherents `Building`. For now, they're just empty scripts, which hopefully will change soon.

I also added the ".DS_Store" files to ".gitignore" in a separated commit (fc32e588e1fdfbe3a3a5019e7971e11a4f0d1cc1).

**Pull request closed without merging**
