### PR TITLE
Working on main menu

### PR DESCRIPTION
**Pull request by Janglee123**
just added icons. although I need guidance.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
Some of the grapfics are already in i think? @aaronfranke

**Comment by Janglee123** [comment]
@LinuxDonald  Yes he added icons but I created same directory as he did.

**Comment by aaronfranke** [comment]
This PR has zero files changed now?

**Comment by Janglee123** [comment]
I updated my repo with upstream and found work is already done.

**Comment by aaronfranke** [comment]
Please rebase and squash your commits. [Godot has a great tutorial on pull request workflow](https://godot.readthedocs.io/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by Janglee123** [comment]
Hey is it ok now ? I added sound in main menu

**Comment by Janglee123** [comment]
Sound is already added in repo that is what I done in PR thus there is no reason for merge. So, closing PR is right option. Actually I got some busy schedule in academics, so I cant contribute for some time but I will surly come back.

**Pull request closed without merging**
