### PR TITLE
Reorganize nodes and resources

### PR DESCRIPTION
**Pull request by aaronfranke**

### CODE REVIEW

**Comment by aaronfranke** [comment]
@YeldhamDev I'm still learning how these merge buttons work, I wanted to see what would happen if I merged your branch before you made the PR yourself, I don't know why it doesn't say you authored.

**Comment by YeldhamDev** [comment]
@aaronfranke Oh, so that's what happened. I thought that I was going nuts and didn't remember committing the PR...

**Comment by YeldhamDev** [comment]
But seriously, you should avoid doing that. Not only because the missing authoring (which while I don't mind that much, there are people that would be lived by such thing), but because the commit could've been not ready yet. You lucked out that this one was.

Anyways, here's a explanation of the PR itself:
- Make the theme resource be place and the root-most node of the scene. Themes are inherited by the children, there's no need to place them in each control.
- Remove some unnecessary `CenterContainers`. Anchoring the controls themselves is already enough in most situations.

**Comment by YeldhamDev** [comment]
@aaronfranke I think there's a quick way to fix this, as it was the last commit, try this:
`git commit --amend --author="Michael Alexsander Silva Dias <michaelalexsander@protonmail.com>"`

**Pull request merged**
