### PR TITLE
Add an intro animation to the main menu

### PR DESCRIPTION
**Pull request by YeldhamDev**
We may have no gameplay yet, but boy, our menu is **sleek**!:

[Intro](https://b2aeaa58a57a200320db-8b65b95250e902c437b256b5abf3eac7.ssl.cf5.rackcdn.com/media_entries/20331/Peek_2019-01-16_19-28.gif)
(The GIF is choppy as hell, but it was the best I could do)

Completely skippable by the way, just press any button in the keyboard/mouse.

### CODE REVIEW

**Comment by aaronfranke** [comment]
Oh man, that is AWESOME! Your video link doesn't work, but it looks great when loaded up. I definitely love the fact that the wheel spins into existence, that's awesome. You are going above and beyond.

Though, the banner's final position seems a bit close to the wheel to me. And I'm also wondering if this is too "busy" of an animation. Perhaps we could make the banner start up top (not move) and the logo image fades out to show the wheel. 

I'm not sure though. What do you think? @LinuxDonald @Beliaar (I don't know who else to ping)

**Comment by YeldhamDev** [comment]
@aaronfranke I've just fixed the link. And about your points:

- The title is close to the helm so it's still visible in smaller screens (such as mine).
- I really don't think it's that busy, specially for a intro. Besides, in the game's logo, the title is also below the emblem.

**Comment by aaronfranke** [comment]
Wow, you must have a very small screen. Looking at your GIF vs the video, the logo isn't centered on large screens. On yours it takes up the whole screen. This doesn't seem intentional.

**Comment by YeldhamDev** [comment]
I watched your video, and yep, the logo's size is wrong, which is strange, since the title's size is correct. I made another push, could you test it again?

**Comment by YeldhamDev** [comment]
I think I know the problem. It's because I changed the logo's import settings (SVG scale to '2'), and it seems that Godot didn't update its cache on your side.

**Comment by Beliaar** [comment]
I think it looks good, but I think its rather @LinuxDonald who has a say in this.

**Comment by LinuxDonald** [comment]
I really like it. Really nice :)

**Pull request merged**
