### PR TITLE
Build MacOs dmg file

### PR DESCRIPTION
**Pull request by baptistemesta**
Hi,

I think it would be nice to export the game for MacOs.
Tested it right now, It looks like it works as expected.

### CODE REVIEW

**Comment by Calinou** [comment]
Note that exporting a DMG file can only be done from macOS as it depends on system utilities. On other platforms, you can only export to a ZIP archive containing the application bundle.

**Comment by baptistemesta** [comment]
> Note that exporting a DMG file can only be done from macOS as it depends on system utilities. On other platforms, you can only export to a ZIP archive containing the application bundle.

I did not know that, I expected it to work since I was able to generate `.exe` on mac.
If this does not work on other platforms, we can revert it or I can change the behavior to only generate .dmg optionally.

**Comment by aaronfranke** [comment]
Can you add an `if` statement to detect MacOS, and only execute these lines if it is MacOS?

**Comment by baptistemesta** [comment]
I'll try

**Comment by baptistemesta** [comment]
Done here:
https://github.com/unknown-horizons/godot-port/pull/54

**Pull request merged**
